title: Djouher Alili
logo: /assets/img/circle.jpeg
description: Welcome to my portfolio! Dive in and explore. Questions or collaborations? Email me at alili.djouher@gmail.com. Let's connect! 👋
show_downloads: false
theme: jekyll-theme-minimal
