title: Djouher Alili
logo: /assets/img/circle.jpeg
description: 
Candidate possesses a B.Sc. in Mathematics & Statistics and Computer Science from Concordia University,
enriched by hands-on experience in financial analysis and software development during internships in banking and other industries. 
Demonstrates adeptness in data-driven decision-making and software engineering, with a focus on delivering solutions that drive efficiency 
and growth. 
Eager to leverage analytical skills and technical proficiency in an entry-level role to contribute to organizational success and innovation.
show_downloads: false
theme: jekyll-theme-minimal
